### ISSUE TITLE
card emulation

### ISSUE THREAD

**Issue by n4lexeev** [EddyVerbruggen/nativescript-nfc#10]
is any tutorial for card emulation of device ?
thx for advance

**Comment by EddyVerbruggen** [comment]
Dunno, but if you find one, feel free to post it here.

**Comment by Nurgunkalol** [comment]
I am trying to do like this:
declare var android: any;
@JavaProxy("com.tns.MyHostAdpuService")
class MyHostAdpuService extends android.nfc.cardemulation.HostAdpuService { }

also added it to AndroidManifest but tns-nativescript-declarations doesnt see android.nfc.cardemulation
+ on testing with scanner its always shows "unable to instantiate service classnotfoundexception"

can anyone give me advance how to do it

**Comment by n4lexeev** [comment]
Im done NFC HostApduService (nativescript app works like card emulation for android):
```
declare var android: any;

@javaproxy("com.tns.HostApduService")
class MyHostApduService extends android.nfc.cardemulation.HostApduService{ 

onDeactivated(reason: number) { }

processCommandApdu(commandApdu: Int8Array, extras?: android.os.Bundle): {
  // your code 
}

}
```

works great!

**Comment by morALE-jo** [comment]
Hi @Nurgunkalol I'm in the process of developing a NativeScript app that needs host-based card emulation (HCE) to pay in readers connected to arcade games and it seems like there is not much information about this topic. I noticed that you managed to create a functional app.
Would it be too much if I ask for a running code example if you have it at hand?

**Comment by harfyt** [comment]
> android.nfc.cardemulation.HostApduService

Hello @n4lexeev, could you share a complete example of how did you manage to send an NDEF message ?
