### ISSUE TITLE
setOnNdefDiscoveredListener callback is not invoked on main thread in iOS

### ISSUE THREAD

**Issue by manojdcoder** [EddyVerbruggen/nativescript-nfc#11]
In iOS `setOnNdefDiscoveredListener` callback not seems to be invoked on main thread due to which updating UI elements / `changeDetectorRef.detectChanges()` in angular app doesn't work.

A workaround was using a `Promise.resolve().then(()=>{})` inside callback, but fixing this in the plugin will make it parity with Android.

**Comment by EddyVerbruggen** [comment]
Perfect finding, and thanks for the hint!

I've also piggybacked a fix for iOS where certain encoded Ndef data would crash the app.

**Comment by MaxiSonntag** [comment]
Not sure if it's just me but I currently had the same issue with Android. My workaraound was injecting  `NgZone` to the component and using the `run` method for all UI relevant operations.

Not sure if I did something wrong or this issue still persists?
