### ISSUE TITLE
Question: iOS support

### ISSUE THREAD

**Issue by fhackenb** [EddyVerbruggen/nativescript-nfc#18]
Are you planning to add iOS support for the remaining functions that are android only?

I'm particularly interested in the writeTag function

**Comment by EddyVerbruggen** [comment]
Please reopen with a link to the Apple docs on how to do that, and I'll gladly give it a try.

**Comment by fhackenb** [comment]
Ahh looks like Apple doesn't let you do writes - hopefully they'll add that at some point.
