### ISSUE TITLE
Plugin affects navigation in Nativescript with Angular app after installation (Android)

### ISSUE THREAD

**Issue by neilsb** [EddyVerbruggen/nativescript-nfc#2]
After installing the nativescript-nfc angular plugin navigation stopped working after the back button was pressed on an android device.

Both **[nsRouterLink]** in the html or **routerExtensions.navigate()** in typescript fail to produce navigation or an error message.

Can be reproduced simply by creating a new app from the template and installing teh nativescript-nfc plugin.

    tns create testApp --ng
    tns plugin add nativescript-nfc

After the plugin installation, the first tap to view item detail will work fine, but after tapping back further taps will not result in any item detail being displayed.

**Comment by EddyVerbruggen** [comment]
Hi,

I created the app according to your instructions and added the plugin. Then ran `tns run ios` and navigated back and forth.. doesn't break. Do I need to do anything else to reproduce it? Like importing the plugin for instance?

**Comment by neilsb** [comment]
I've not tested on ios yet, but should be able to do that this evening and let you know, but I can reproduce it on android.

Simply adding the plugin is enough to cause the error, and as I result I suspect that the problem is to do with hooking into the Android Activities and Intents, since that part exectuted on application startup as soon as the plugin has been added to the project.

**Comment by EddyVerbruggen** [comment]
I can imagine that being true, but I just tried the same on Android 7 and there's no problem there either. So maybe I'm missing a step. Are you sure I don't need to require/import the plugin?

**Comment by neilsb** [comment]
Hi,

Myself and my colleague both experienced the same problem on both the android emulator and android devices (versions 4, 6 and 7).  Let me try ios later on and I'll spin up a new VM and re-check on Android with a clean install and I'll get back to you.

**Comment by neilsb** [comment]
I can confirm the issue does not show itself when running in the iPhone simulator.

On a Windows 10, with a fresh install following the Nativescript documentation the issue can be reproduced when running on the android emulator or a connected android device however. 

Edit:  Just tested on the Android Emulator on OS X and the error is reproducable on that also.

**Comment by EddyVerbruggen** [comment]
Let me run it on Android this weekend and get back to you. Thanks for your tests!
