### ISSUE TITLE
demo will not build

### ISSUE THREAD

**Issue by mediadeo** [EddyVerbruggen/nativescript-nfc#25]
Hello I tried to implement this NFC scanner but all I get on android is a beep and then nothing happens. 

In order to try and figure out what I'm doing wrong I downloaded this demo repo and then tried to do a cloud build with that on NS, but it failed...

I'm also trying in JS and your demo is in TS ... but after half a day of trial and error, I'm kind of stuck without any pointers?

**Comment by EddyVerbruggen** [comment]
Please share a repo that shows the problem, I may find some time to take a look.

**Comment by EddyVerbruggen** [comment]
Should be OK now.
