### ISSUE TITLE
Not compatible with nativescript 5.0.0

### ISSUE THREAD

**Issue by patricklx** [EddyVerbruggen/nativescript-nfc#26]
App crashes at startup, probably because they switched to FragmentActvity?

`Event: activityResumed, Activity: com.tns.NativeScriptNfcActivity@1ed9f66
System.err: com.tns.NativeScriptException:
System.err: Calling js method onViewAttachedToWindow failed
System.err:
System.err: TypeError: this._context.getSupportFragmentManager is not a function
System.err: File: "file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 190, column: 46
System.err:
System.err: StackTrace:
System.err:     Frame: function:'View._getRootFragmentManager', file:'file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 190, column: 47
System.err:     Frame: function:'View._getFragmentManager', file:'file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 215, column: 32
System.err:     Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 134, column: 28
System.err:     Frame: function:'Frame._onAttachedToWindow', file:'file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 118, column: 14
System.err:     Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/com.ibm.hrl.workright/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 35, column: 27
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at com.tns.gen.java.lang.Object_frame_29_36_AttachListener.onViewAttachedToWindow(Object_frame_29_36_AttachListener.java:17)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:15568)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2955)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1656)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:735)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:667)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
System.err:     at android.os.Handler.handleCallback(Handler.java:761)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:156)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

**Comment by EddyVerbruggen** [comment]
Should be OK now.
