### ISSUE TITLE
Update readme - when using webpack - Reference the nfc activity 

### ISSUE THREAD

**Issue by codebeast** [EddyVerbruggen/nativescript-nfc#31]
Would be worth updating readme for webpack users or they will run into activity being not found

- "nativescript-nfc/nfc-activity.android.js" to be referenced in the appComponents

**Comment by EddyVerbruggen** [comment]
Can you send a PR to this section please? https://github.com/EddyVerbruggen/nativescript-nfc#webpack

**Comment by EddyVerbruggen** [comment]
No longer needed with the 4.x release of this plugin.
