### ISSUE TITLE
package.json missing for demo app

### ISSUE THREAD

**Issue by CorporateDrone** [EddyVerbruggen/nativescript-nfc#33]
Hello, Thanks for making this plugin. I downloaded the code and am trynna ing to run your demo.  When I run `npm run demo.android` at the root of the project, I receive  gives the following error:

`npm ERR! enoent ENOENT: no such file or directory, open '/Projects/nativescript-nfc-master/package.json'`
`npm ERR! enoent This is related to npm not being able to find a file.`

Is there something else I can try?

**Comment by EddyVerbruggen** [comment]
Try doing `cd src` first.

**Comment by CorporateDrone** [comment]
That worked, thanks!
