### ISSUE TITLE
how to view  NFC Tags ID on setOnTag?

### ISSUE THREAD

**Issue by Efrenray** [EddyVerbruggen/nativescript-nfc#47]
my School ID has NFC tag in it and would like to view its data.
Itried the setOnNdef and returned this:

 > Tag discovered, but no listener was set via setOnTagDiscoveredListener. Ndef: {"id":[86,56,70,70],"techList":["android.nfc.tech.NfcA","android.nfc.tech.MifareClassic","android.nfc.tech.NdefFormatable"]}

also did the setOnTag and returned:

> Discovered a tag with ID 86,56,70,70

I'd like to view the data on the ID before writing on it. is this possible?

**Comment by EddyVerbruggen** [comment]
Should work, when `setOnTagDiscoveredListener` is set. Just try and run the demo.
