### ISSUE TITLE
Cannot find namespace 'android'

### ISSUE THREAD

**Issue by Rav-Naz** [EddyVerbruggen/nativescript-nfc#51]
after type in console `tns run` I'm getting this error:

```
ERROR in node_modules/nativescript-nfc/nfc.android.d.ts:3:18 - error TS2503: Cannot find namespace 'android'.

3     savedIntent: android.content.Intent;
                   ~~~~~~~
node_modules/nativescript-nfc/nfc.android.d.ts:11:22 - error TS2503: Cannot find namespace 'android'.

11     ndefToJSON(ndef: android.nfc.tech.Ndef): NfcNdefData;
                        ~~~~~~~
node_modules/nativescript-nfc/nfc.android.d.ts:12:28 - error TS2503: Cannot find namespace 'android'.

12     messageToJSON(message: android.nfc.NdefMessage): Array<NfcNdefRecord>;
                              ~~~~~~~
node_modules/nativescript-nfc/nfc.android.d.ts:13:26 - error TS2503: Cannot find namespace 'android'.

13     recordToJSON(record: android.nfc.NdefRecord): NfcNdefRecord;
                            ~~~~~~~
```

I'm working on Android Emulator, in Nativescript Angular

**Comment by EddyVerbruggen** [comment]
Thx for reporting. There are a few ways around this, but I think it's best to fix that in the plugin itself - give 4.1.0 a spin.

**Comment by Rav-Naz** [comment]
I'm fixed it by install tns-platform-declarations and added reference.d.ts
on root folder. I'm suggest that you should add this  infromation in
readme.md.

śr., 6 lis 2019, 17:18 użytkownik Eddy Verbruggen <notifications@github.com>
napisał:

**Comment by EddyVerbruggen** [comment]
That was what I could have said, but I did one better and fixed it in the plugin like I mentioned.

**Comment by Rav-Naz** [comment]
Hey, is there any way to enable NFC only in one component? Already it is
enabled on whole application, and everytime I'm getting this information:

*Ndef discovered, but no listener was set via setOnNdefDiscoveredListener. *

I'm wish to use nfc only in components where I have listeners.
Thanks for help in advance.
Best regards, Rafał

śr., 6 lis 2019 o 18:37 Eddy Verbruggen <notifications@github.com>
napisał(a):

**Comment by EddyVerbruggen** [comment]
We can remove that console.log, if that helps. But please don't hijack other issues with unrelated questions.
