### ISSUE TITLE
possibility to undo setOnNdefDiscoveredListener

### ISSUE THREAD

**Issue by wendt88** [EddyVerbruggen/nativescript-nfc#59]
after you add a `listener` with `setOnNdefDiscoveredListener` you can't remove it.
it would be a nice implementation.
if I'm not wrong, an android you have only to set `onNdefDiscoveredListener = null;`
and on iOS to call `invalidate()` on that session

**Comment by demetrius-tech** [comment]
Doesn't setOnNdefDiscoveredListener(null) removes the listener?

**Comment by wendt88** [comment]
sure, my fault... did not seen
