### ISSUE TITLE
Android setOnTagDiscoveredListener Error

### ISSUE THREAD

**Issue by kunchit** [EddyVerbruggen/nativescript-nfc#7]
i use **setOnNdefDiscoveredListener** and implement like this 
 `exports.doStartTagListener = function(){
  nfc.setOnTagDiscoveredListener(function(data) {
    console.log("Discovered a tag with ID " + data.id);
  }).then(
    function() {
      console.log("OnTagDiscovered listener added");
    }
  );
}
`
 When i read rfid . i found error 

> JS: Tag discovered, but no listener was set via setOnTagDiscoveredListener. Ndef: {"id":[94,-11,-7,114],"techList":["android.nfc.tech.MifareClassic","android.nfc.tech.NfcA","android.nfc.tech.NdefFormatable"]}

I need to get data from rfid and alert to screen . How can i implement this function.

**Comment by EddyVerbruggen** [comment]
Hi, if you can reproduce this error with the demo app in the repo then I'll gladly take a look!
