### ISSUE TITLE
Bounty for write function in IOS

### ISSUE THREAD

**Issue by timh5** [EddyVerbruggen/nativescript-nfc#77]
Hi Eddy, thank you so much for this amazing library!
What will it take to get iOS write working? It is a technological barrier with the software, or is it possible with some extra work?

I am interested in hiring you or someone to build this, or hire for consulting so you can direct us how to do this?
What do you think? @EddyVerbruggen

**Comment by demetrius-tech** [comment]
@timh5 check #52

**Comment by timh5** [comment]
@demetrius-tech amazing! Thanks.
