### ISSUE TITLE
Webpack Issues Angular

### ISSUE THREAD

**Issue by skhye05** [EddyVerbruggen/nativescript-nfc#8]
### When i am installing the plugin and running webpack command i am getting the following error
`Execution failed for task ':asbg:generateBindings'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_144\bin\java.exe'' finished with non-zero exit value 1
`

**Comment by EddyVerbruggen** [comment]
That's an incredibly unuseful error message.. can't help with that.

**Comment by skhye05** [comment]
@EddyVerbruggen Did you ever run into an error with webpack while using the plugin with nativescript + angular??

**Comment by EddyVerbruggen** [comment]
I have never done that with this plugin.

That being said, I have a non-Angular webpack configuration in the [Travis CI build](https://github.com/EddyVerbruggen/nativescript-nfc/blob/master/.travis.yml). And this build succeeds.

**Comment by skhye05** [comment]
@EddyVerbruggen How can i exclude it from webpack?? and if i do will it work??

**Comment by manojdcoder** [comment]
@EddyVerbruggen I'm using this plugin with Angular and WebPack, iOS complies just fine but there is known issue with [Android](https://github.com/NativeScript/nativescript-cli/issues/2901)

As @Pip3r4o suggested, I simply renamed the JavaProxy and updated same in manifest, everything was just perfect then. It may not be a feasible solution but at least the build is happening for now.

**Comment by EddyVerbruggen** [comment]
@manojdcoder Would you be willing to do a PR to change that?

**Comment by EddyVerbruggen** [comment]
If it were trivial I'd do it immediately but I'm thinking about the implications still.

What if 2 plugins would need a changed activity name? So I don't really like this fix (although it was recommended in the issue you linked to)... so need some time to digest it.

**Comment by manojdcoder** [comment]
@EddyVerbruggen Exactly that is the same reason I felt this is not a feasible solution. But for time being I had to go with this.

**Comment by manojdcoder** [comment]
If [onNewIntent](https://github.com/NativeScript/NativeScript/issues/2747) is implemented in NS Activity, this could be easier.
